version: '3.8'

services:
  django:
    container_name: django
    build:
      context: /home/hbay/Desktop/docker/app/back-end/
    restart: always
    volumes:
      - /home/hbay/Desktop/halimus:/app
    ports:
      - "8000:8000"  # Dışarıya 8000 portu açılıyor
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://username:password@db:5432/mydatabase
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: