# Generated by Django 4.2.17 on 2025-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_active',
            field=models.BooleanField(default=False),
        ),
    ]
