services:
  django:
    container_name: django
    build:
      context: /home/hbay/Desktop/ft_transcendence/docker
      dockerfile: /home/hbay/Desktop/ft_transcendence/docker/app/back-end/Dockerfile
    restart: always
    volumes:
      - /home/hbay/Desktop/ft_transcendence/halimus:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://username:password@postgre:5432/mydatabase
    depends_on:
      - postgre
  postgre:
    container_name: postgre
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
