# Generated by Django 4.0 on 2025-01-29 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcendence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_alias', models.CharField(max_length=100)),
                ('tournament_name', models.CharField(max_length=100)),
                ('players', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('win_count', models.IntegerField(default=0)),
                ('lose_count', models.IntegerField(default=0)),
                ('score', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('opponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_history', to='transcendence.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history', to='transcendence.user')),
            ],
        ),
    ]
