# Generated by Django 4.0 on 2025-02-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transcendence', '0001_initial'),
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pong.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transcendence.user')),
            ],
        ),
    ]
